### ISSUE TITLE
Fix tests that are executed failed

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#120]
Those tests are failed to be executed, founded in #119.

- [x] test_tests__esbuild__default__arrow_fn_scope__test_config_json
- [x] https://github.com/rolldown-rs/rolldown/issues/135
- [x] test_tests__esbuild__default__const_with_let__test_config_json
- [x] #136
- [ ] test_tests__esbuild__default__forbid_const_assign_when_bundling__test_config_json
- [x] test_tests__esbuild__default__forbid_const_assign_when_lowering_using__test_config_json
- [ ] test_tests__esbuild__default__import_missing_common_js__test_config_json
- [ ] test_tests__esbuild__default__import_then_catch__test_config_json
- [ ] test_tests__esbuild__default__nested_require_without_call__test_config_json
- [ ] test_tests__esbuild__default__preserve_key_comment__test_config_json
- [ ] test_tests__esbuild__default__require_property_access_common_js__test_config_json
- [ ] test_tests__esbuild__default__require_resolve__test_config_json
- [ ] test_tests__esbuild__default__require_without_call__test_config_json
- [ ] test_tests__esbuild__default__this_inside_function__test_config_json
- [ ] test_tests__esbuild__default__var_relocating_bundle__test_config_json
- [ ] test_tests__esbuild__import_star__import_namespace_undefined_property_side_effect_free_file__test_config_json
- [x] test_tests__esbuild__import_star__import_of_export_star__test_config_json
- [x] test_tests__esbuild__import_star__import_of_export_star_of_import__test_config_json
- [x] test_tests__esbuild__splitting__shared_commonjs_into_es6__test_config_json

## Enhancements

Not bug.

- [ ] test_tests__esbuild__default__dynamic_import_with_template_iife__test_config_json

**Comment by Demivan** [comment]
`test_tests__esbuild__default__preserve_key_comment__test_config_json` is blocked by https://github.com/oxc-project/oxc/issues/1046. Oxc does not support printing comments. But I have fixed the snapshot - it had incorrect syntax: #492

**Comment by AliceLanniste** [comment]
`tests__esbuild__default__var_relocating_bundle__test_config_json` is improper order because of
https://github.com/rolldown/rolldown/blob/06cf72d80e4439e1539ddac1a6ddaceacb13a0c5/crates/rolldown/tests/common/case.rs#L69.
I tried to delete the line and get the proper order,but it will affect other tests's order. So I suggest providing a key property to sort by filename.

**Comment by komyg** [comment]
Hi, I'd like to contribute fixing these tests. Are they still broken?

**Comment by IWANABETHATGUY** [comment]
Not needed.
