### ISSUE TITLE
[Bug]: Dynamically importing JSON with `output.advancedChunks.groups` crashes >1.0.0-beta.1

### ISSUE THREAD

**Issue by thesmartwon** [rolldown/rolldown#3437]
### Reproduction link or steps

https://stackblitz.com/edit/github-e1benpcb?file=rolldown.config.mjs

### What is expected?

No crash

### What is actually happening?

```
thread '<unnamed>' panicked at crates/rolldown_common/src/types/symbol_ref_db.rs:143:7:
canonical name not found for SymbolRef { owner: 0, symbol: SymbolId(9) }, original_name: "__esm"
```

### System Info

```Shell
rolldown >1.0.0-beta.1
```

### Any additional comments?

The `rolldown:runtime` chunk isn't special. If I try creating any valid chunks it'll crash.

**Comment by thesmartwon** [comment]
If it provides any hints, I'm also able to reproduce this error in watch mode without setting `output.advancedChunk`s on `1.0.0-beta.3` here: https://github.com/openbible-io/frontend/blob/bf6f608363ee90d967554bc89cd787b8160ca8bc/build/config.ts

Wasn't able to quickly reproduce in a stackblitz.

**Comment by lansi951** [comment]
It was fixed in 89db1f3 commit.
Have you tried `1.0.0-beta.3-commit.bc5b1e7` version?

**Comment by IWANABETHATGUY** [comment]
> It was fixed in [89db1f3](https://github.com/rolldown/rolldown/commit/89db1f3553e69e7157a11ae196a6a690ec6d1c99) commit. Have you tried `1.0.0-beta.3-commit.bc5b1e7` version?

Maybe they are not same issues, I tried latest commit but the issue still exists.

**Comment by thesmartwon** [comment]
> It was fixed in https://github.com/rolldown/rolldown/commit/89db1f3553e69e7157a11ae196a6a690ec6d1c99 commit.
Have you tried 1.0.0-beta.3-commit.bc5b1e7 version?

Still happens in that version. I updated the stackblitz.

**Comment by shulaoda** [comment]
It seems that this issue was caused by #3343.

https://github.com/rolldown/rolldown/pull/3343/files#diff-035ce9006e573c9e7d8ea10510bcf1b73f4fa35cd515dd88df96c1d36cd34581L463-R460

**Comment by thesmartwon** [comment]
Thank you @shulaoda !
